import libs = glfw%lib{glfw}

# Bundled third-party libraries.
#
libue{tinycthread}: obje{tinycthread}: {h c}{"$src_root"/../upstream/deps/tinycthread}
libue{getopt}:      obje{getopt}:      {h c}{"$src_root"/../upstream/deps/getopt}
libue{glad_vulkan}:                    {h  }{"$src_root"/../upstream/deps/glad/vulkan}

# Preprocessor search path for bundled headers.
#
c.poptions += -I"$src_root"/../upstream/deps/

# Link against the standard math library (libm).
#
if ($c.target.class != 'windows')
  c.libs += -lm

./: exe{driver}: {h c}{**} libue{glad_vulkan} $libs
