import libs = glfw%lib{glfw}

# Bundled third-party libraries.
#
./: libue{tinycthread}: {h c}{"$src_root"/deps/tinycthread}
./: libue{getopt}:      {h c}{"$src_root"/deps/getopt}
./: libue{glad_vulkan}: {h  }{"$src_root"/deps/glad/vulkan}

# Preprocessor search path for bundled headers.
#
c.poptions += -I"$src_root"/deps/

# Link against the standard math library (libm).
#
if ($c.target.class != 'windows')
  c.libs += -lm

./: exe{driver}: {h c}{**} libue{glad_vulkan} $libs
