./: {*/ -build/ -deps/} manifest

# Mark all third-party source files (headers and sources) under deps/ for
# distribution.
#
./: {h c}{deps/**}: dist = true

# Don't install tests.
#
tests/: install = false
