import libs = glfw%lib{glfw}

libue{tinycthread}: {h c}{deps/tinycthread}
libue{getopt}: {h c}{deps/getopt}
libue{glad_gl}: c{deps/glad_gl} h{deps/glad/gl}

for n: boing gears heightmap offscreen particles \
        sharing simple splitview wave
{
    ./: exe{$n}: c{$n} $libs libue{glad_gl}
}

exe{particles}: libue{tinycthread} libue{getopt}

c.poptions += "-I$src_root/deps/"

exe{*}: install = false