import libs = glfw%lib{glfw}
include ../deps/ # Local project import

# Order of linking between tinycthread and glfw (with pthread) is important
libs =+ ../deps/liba{glad_gl} ../deps/liba{tinycthread}

for n: empty gamma icon inputlag joysticks opacity tearing \
        threads timeout title windows
{
    ./: exe{$n}: c{$n} $libs
}

./: exe{triangle-vulkan}: c{triangle-vulkan} ../deps/liba{glad_vulkan} $libs