import libs = glfw%lib{glfw}
include ../deps/ # Project local

for n: clipboard events msaa glfwinfo \
        iconify monitors reopen cursor
{
    ./: exe{$n}: c{$n} ../deps/liba{getopt} ../deps/liba{glad_gl} $libs
}

exe{glfwinfo}: ../deps/liba{glad_vulkan}
exe{glfwinfo}: test = true
exe{glfwinfo}: testscript{glfwinfo}
exe{monitors}: testscript{monitors}