import libs = glfw%lib{glfw}

# Bundled third-party libraries.
#
libue{glad_gles2}: {h}{"$src_root"/../upstream/deps/glad/gles2}

# Preprocessor search path for bundled headers.
#
c.poptions += -I"$src_root"/../upstream/deps/

# Link against the standard math library (libm).
#
if ($c.target.class != 'windows')
  c.libs += -lm

./: exe{driver}: {h c}{**} libue{glad_gles2} $libs
